name: Build

on:
  push:
    branches: [ main ]

jobs:
  
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        
      - name: heroku login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: remove previous app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_NAME: ${{ secrets.APP_NAME }}
        run: heroku apps:destroy $APP_NAME --confirm $APP_NAME
      
      - name: create app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_NAME: ${{ secrets.APP_NAME }}
        run: heroku create $APP_NAME
        
      - name: set config
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          TOKEN: ${{ secrets.TOKEN }}
          SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
          BOT_ENDPOINT: ${{ secrets.BOT_ENDPOINT }}
        run: heroku config:set TOKEN=$TOKEN SIGNING_SECRET=$SIGNING_SECRET BOT_ENDPOINT=$BOT_ENDPOINT
        
      - name: push app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_NAME: ${{ secrets.APP_NAME }}
        working-directory: ./SlackBotProject
        run: heroku container:push web -a $APP_NAME
        
      - name: release app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_NAME: ${{ secrets.APP_NAME }}
        run: heroku container:release web -a $APP_NAME
